### ISSUE TITLE
Example: 'framework not found SDL2' when attempting to run 'haxe build.hxml'

### ISSUE THREAD

**Issue by jackwlee01** [swordcube/hxsdl#1]
On Mac OS (M1 Ventura 13.4) when attempting to run `haxe build.hxml` in the `basic-image-test` folder I am getting the following error:

```
Link: Test
ld: framework not found SDL2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: Build failed
```

**Comment by swordcube** [comment]
I'm not sure how i can fix the issue since i do not have a mac to test this issue on, but i'm gonna make a quick commit to see if that maybe fixes it

**Comment by swordcube** [comment]
Closing since there hasn't been any response for like a month

**Comment by swordcube** [comment]
I think you can still comment after a issue has been closed so like do that if you still have issues
